// demo.js - vzorove pozemky pre ukazku UI
const DEMO_PARCELS = [
  {
    title: "IBV pozemok Senec - pri centre",
    url: "https://nehnutelnosti.sk/demo/1",
    price_eur: 38000,
    area_sqm: 820,
    location_text: "Senec, Bratislavsky kraj",
    parcel_number: "1234/5",
    lat: 48.219, lon: 17.397,
  },
  {
    title: "Stavebny pozemok Pezinok - tichy okraj",
    url: "https://nehnutelnosti.sk/demo/2",
    price_eur: 45000,
    area_sqm: 950,
    location_text: "Pezinok, Bratislavsky kraj",
    parcel_number: "567/8",
    lat: 48.289, lon: 17.266,
  },
  {
    title: "Lacny pozemok Malacky - velka plocha",
    url: "https://nehnutelnosti.sk/demo/3",
    price_eur: 22000,
    area_sqm: 1200,
    location_text: "Malacky, Bratislavsky kraj",
    parcel_number: "891/2",
    lat: 48.434, lon: 17.024,
  },
  {
    title: "Pozemok Stupava - blizko Bratislavy",
    url: "https://nehnutelnosti.sk/demo/4",
    price_eur: 55000,
    area_sqm: 700,
    location_text: "Stupava, Bratislavsky kraj",
    parcel_number: "321/6",
    lat: 48.274, lon: 17.027,
  },
  {
    title: "Oracia poda Gbely - daleko ale lacno",
    url: "https://nehnutelnosti.sk/demo/5",
    price_eur: 12000,
    area_sqm: 1400,
    location_text: "Gbely, Skalica okres",
    parcel_number: "741/3",
    lat: 48.718, lon: 17.115,
  },
];
