name: snapcall
description: Snap a number. Make the call. - OCR phone number scanner app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  google_mlkit_text_recognition: ^0.13.0
  url_launcher: ^6.2.0
  permission_handler: ^11.3.0
  path_provider: ^2.1.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/